// AUTO-GENERATED — Swift 소스(Gacha.pool · PetCollection.members · PetSkills.uniqueTable/풀)에서 파싱. 직접 편집 금지.
// 재생성: scripts/gen_pet_meta.py (펫 추가/등급변경/고유기·베이스 스킬 변경 시). 195 kinds, 34 unique.
// 서버 authoritative 스탯/스킬 계산에 필요(클라는 하드코딩하지만 서버엔 없어서 포팅).

export const RARITY: Record<string,string> = {
  agentMike: "common",
  akita: "common",
  angel: "common",
  angie: "common",
  angryPig: "common",
  antennaBot: "common",
  archer: "mythic",
  armand: "rare",
  baldPirate: "rare",
  ballooney: "common",
  barryCherry: "common",
  bat: "common",
  batBot: "rare",
  beaconBot: "common",
  bear: "common",
  bee: "common",
  bigDemon: "epic",
  bigGuy: "rare",
  bigRed: "common",
  bigZombie: "rare",
  blankey: "common",
  blockyBub: "common",
  blueBird: "common",
  boar: "common",
  bombGuy: "common",
  bub: "common",
  bumpyBot: "rare",
  bunny: "common",
  bushly: "common",
  cat1: "common",
  cat2: "common",
  cat3: "common",
  cat4: "common",
  cat5: "common",
  cat6: "common",
  caveGirl: "common",
  caveGirl1: "common",
  caverman: "rare",
  chameleon: "rare",
  cheesePuff: "common",
  chiChiBird: "common",
  chicken: "common",
  chort: "common",
  clownCaptain: "epic",
  cucumber: "common",
  daikon: "common",
  deer: "common",
  devoDevil: "rare",
  diego: "rare",
  dinoBat: "common",
  dinoBug: "common",
  dinoDragon: "epic",
  dinoLizard: "rare",
  dinoPlant: "rare",
  dinoTurtle: "common",
  diverFish: "common",
  doc: "rare",
  dragonMan: "rare",
  duck: "common",
  dwarfF: "common",
  dwarfM: "rare",
  elfF: "common",
  elfM: "rare",
  evilWizard: "rare",
  fairy: "epic",
  fantasyWarrior: "rare",
  fatBird: "common",
  fierceTooth: "rare",
  fireWorm: "rare",
  flyingEye: "rare",
  fox: "common",
  geralt: "epic",
  ghost: "epic",
  giantRat: "common",
  gloppySlime: "common",
  goblin: "common",
  goblinBrute: "rare",
  goldenRetriever: "common",
  gordon: "epic",
  greatDane: "common",
  grizzly: "rare",
  gumBot: "common",
  hermie: "common",
  heroKnight: "epic",
  holly: "rare",
  huntress: "epic",
  husky: "common",
  iceZombie: "common",
  imp: "common",
  jellySlime: "common",
  jumpyLumpy: "common",
  kingHuman: "epic",
  kingPig: "rare",
  kingSlime: "common",
  knightF: "epic",
  knightM: "legendary",
  lancer: "mythic",
  lilWiz: "rare",
  lionWarrior: "rare",
  littleCaveBoy: "common",
  lizardF: "common",
  lizardM: "rare",
  martialHero: "rare",
  martianRed: "common",
  maskDude: "epic",
  maskedOrc: "rare",
  medievalKing: "legendary",
  mimic: "rare",
  miniBot: "common",
  miniRex: "rare",
  moeScotty: "common",
  monk: "mythic",
  mrChomps: "rare",
  mrCircuit: "common",
  mrMan: "rare",
  mrMochi: "epic",
  muddy: "common",
  mushroom: "rare",
  myconid: "common",
  necromancer: "rare",
  ninjaFrog: "legendary",
  octi: "common",
  ogre: "epic",
  onionLad: "rare",
  oposum: "common",
  orangeFruit: "common",
  orc: "epic",
  orcShaman: "rare",
  orcWarrior: "rare",
  orchidOwl: "common",
  pawn: "mythic",
  penguin: "common",
  percy: "common",
  pig: "common",
  pigBomber: "common",
  pigBoxer: "common",
  pirateCaptain: "legendary",
  pixelBot: "rare",
  plant: "epic",
  pokeyBub: "common",
  princessSera: "epic",
  pterodactyl: "epic",
  pumpkinDude: "common",
  rabbit: "common",
  radish: "rare",
  rino: "rare",
  roach: "common",
  roboPumpkin: "common",
  roboRetro: "epic",
  roboTotem: "rare",
  robotJ5: "rare",
  robotWalky: "common",
  rock1: "rare",
  rock2: "rare",
  rock3: "rare",
  rocketCherry: "common",
  rollingNero: "common",
  saintBernard: "common",
  schnauzer: "common",
  scrapBot: "common",
  sentryBot: "rare",
  skelet: "common",
  skeletonG: "common",
  skeletonLord: "epic",
  skull: "epic",
  slime: "rare",
  slug: "common",
  snail: "common",
  snipCrab: "common",
  spiderBot: "common",
  spikeyBub: "common",
  squirmyWormy: "common",
  sunFox: "rare",
  sunFrog: "common",
  swampy: "common",
  tRex: "legendary",
  tinySlug: "common",
  tinyZombie: "common",
  toggle: "rare",
  tommy: "rare",
  tracy: "rare",
  trunk: "rare",
  turtle: "common",
  twiggy: "common",
  vampireBat: "common",
  vessa: "common",
  visorBot: "epic",
  warrior: "mythic",
  whale: "legendary",
  wispyFire: "common",
  wizardF: "rare",
  wizardM: "epic",
  wogol: "common",
  wolf: "common",
  zombie: "common",
};

export const COLLECTION: Record<string,string> = {
  agentMike: "helloWorld",
  akita: "emotionalSupport",
  angel: "tokenBurners",
  angie: "todoSince2019",
  angryPig: "nodeModules",
  antennaBot: "ciRunners",
  archer: "onCall",
  armand: "vibeCoders",
  baldPirate: "noVerify",
  ballooney: "helloWorld",
  barryCherry: "helloWorld",
  bat: "dns",
  batBot: "ciRunners",
  beaconBot: "ciRunners",
  bear: "mainframe",
  bee: "dns",
  bigDemon: "fridayDeploy",
  bigGuy: "noVerify",
  bigRed: "fridayDeploy",
  bigZombie: "wontfix",
  blankey: "wontfix",
  blockyBub: "helloWorld",
  blueBird: "dns",
  boar: "mainframe",
  bombGuy: "noVerify",
  bub: "helloWorld",
  bumpyBot: "helloWorld",
  bunny: "mainframe",
  bushly: "todoSince2019",
  cat1: "emotionalSupport",
  cat2: "emotionalSupport",
  cat3: "emotionalSupport",
  cat4: "emotionalSupport",
  cat5: "emotionalSupport",
  cat6: "emotionalSupport",
  caveGirl: "deprecated",
  caveGirl1: "deprecated",
  caverman: "deprecated",
  chameleon: "npmInstall",
  cheesePuff: "helloWorld",
  chiChiBird: "dns",
  chicken: "dns",
  chort: "fridayDeploy",
  clownCaptain: "noVerify",
  cucumber: "noVerify",
  daikon: "helloWorld",
  deer: "mainframe",
  devoDevil: "fridayDeploy",
  diego: "vibeCoders",
  dinoBat: "deprecated",
  dinoBug: "deprecated",
  dinoDragon: "deprecated",
  dinoLizard: "deprecated",
  dinoPlant: "deprecated",
  dinoTurtle: "deprecated",
  diverFish: "helloWorld",
  doc: "tokenBurners",
  dragonMan: "deprecated",
  duck: "dns",
  dwarfF: "vibeCoders",
  dwarfM: "vibeCoders",
  elfF: "vibeCoders",
  elfM: "vibeCoders",
  evilWizard: "tenXEngineer",
  fairy: "todoSince2019",
  fantasyWarrior: "tenXEngineer",
  fatBird: "dns",
  fierceTooth: "noVerify",
  fireWorm: "oomKilled",
  flyingEye: "oomKilled",
  fox: "mainframe",
  geralt: "vibeCoders",
  ghost: "wontfix",
  giantRat: "oomKilled",
  gloppySlime: "todoSince2019",
  goblin: "rustEvangelists",
  goblinBrute: "oomKilled",
  goldenRetriever: "emotionalSupport",
  gordon: "vibeCoders",
  greatDane: "emotionalSupport",
  grizzly: "mainframe",
  gumBot: "ciRunners",
  hermie: "npmInstall",
  heroKnight: "tenXEngineer",
  holly: "vibeCoders",
  huntress: "tenXEngineer",
  husky: "emotionalSupport",
  iceZombie: "wontfix",
  imp: "fridayDeploy",
  jellySlime: "happyPath",
  jumpyLumpy: "helloWorld",
  kingHuman: "tokenBurners",
  kingPig: "nodeModules",
  kingSlime: "oomKilled",
  knightF: "vibeCoders",
  knightM: "vibeCoders",
  lancer: "onCall",
  lilWiz: "tokenBurners",
  lionWarrior: "deprecated",
  littleCaveBoy: "deprecated",
  lizardF: "rustEvangelists",
  lizardM: "rustEvangelists",
  martialHero: "tenXEngineer",
  martianRed: "fridayDeploy",
  maskDude: "vibeCoders",
  maskedOrc: "rustEvangelists",
  medievalKing: "tenXEngineer",
  mimic: "oomKilled",
  miniBot: "ciRunners",
  miniRex: "deprecated",
  moeScotty: "npmInstall",
  monk: "onCall",
  mrChomps: "fridayDeploy",
  mrCircuit: "ciRunners",
  mrMan: "helloWorld",
  mrMochi: "helloWorld",
  muddy: "fridayDeploy",
  mushroom: "todoSince2019",
  myconid: "oomKilled",
  necromancer: "wontfix",
  ninjaFrog: "vibeCoders",
  octi: "helloWorld",
  ogre: "fridayDeploy",
  onionLad: "helloWorld",
  oposum: "happyPath",
  orangeFruit: "helloWorld",
  orc: "rustEvangelists",
  orcShaman: "rustEvangelists",
  orcWarrior: "rustEvangelists",
  orchidOwl: "dns",
  pawn: "onCall",
  penguin: "dns",
  percy: "helloWorld",
  pig: "nodeModules",
  pigBomber: "nodeModules",
  pigBoxer: "nodeModules",
  pirateCaptain: "noVerify",
  pixelBot: "ciRunners",
  plant: "todoSince2019",
  pokeyBub: "helloWorld",
  princessSera: "helloWorld",
  pterodactyl: "deprecated",
  pumpkinDude: "fridayDeploy",
  rabbit: "mainframe",
  radish: "todoSince2019",
  rino: "mainframe",
  roach: "npmInstall",
  roboPumpkin: "ciRunners",
  roboRetro: "ciRunners",
  roboTotem: "ciRunners",
  robotJ5: "ciRunners",
  robotWalky: "ciRunners",
  rock1: "todoSince2019",
  rock2: "todoSince2019",
  rock3: "todoSince2019",
  rocketCherry: "helloWorld",
  rollingNero: "helloWorld",
  saintBernard: "emotionalSupport",
  schnauzer: "emotionalSupport",
  scrapBot: "ciRunners",
  sentryBot: "ciRunners",
  skelet: "wontfix",
  skeletonG: "wontfix",
  skeletonLord: "oomKilled",
  skull: "wontfix",
  slime: "todoSince2019",
  slug: "npmInstall",
  snail: "npmInstall",
  snipCrab: "npmInstall",
  spiderBot: "ciRunners",
  spikeyBub: "helloWorld",
  squirmyWormy: "npmInstall",
  sunFox: "happyPath",
  sunFrog: "happyPath",
  swampy: "fridayDeploy",
  tRex: "deprecated",
  tinySlug: "npmInstall",
  tinyZombie: "wontfix",
  toggle: "vibeCoders",
  tommy: "helloWorld",
  tracy: "vibeCoders",
  trunk: "todoSince2019",
  turtle: "npmInstall",
  twiggy: "helloWorld",
  vampireBat: "oomKilled",
  vessa: "helloWorld",
  visorBot: "ciRunners",
  warrior: "onCall",
  whale: "noVerify",
  wispyFire: "todoSince2019",
  wizardF: "tokenBurners",
  wizardM: "tokenBurners",
  wogol: "fridayDeploy",
  wolf: "mainframe",
  zombie: "wontfix",
};

// Epic+ per-kind 고유기(id, name). 타입은 서버가 battleTypeOf로 파생, power는 상수(pvp_policy).
export const UNIQUE_SKILL: Record<string,[string,string]> = {
  archer: ["remote_exec", "원격 실행"],
  bigDemon: ["prod_outage", "프로덕션 장애"],
  clownCaptain: ["clown_deploy", "광대 배포"],
  dinoDragon: ["dino_stack", "공룡 스택"],
  fairy: ["pixie_patch", "픽시 패치"],
  geralt: ["prompt_injection", "프롬프트 인젝션"],
  ghost: ["zombie_process", "좀비 프로세스"],
  gordon: ["crunch_mode", "크런치 모드"],
  heroKnight: ["full_refactor", "풀 리팩터"],
  huntress: ["pinpoint_debug", "핀포인트 디버그"],
  kingHuman: ["legacy_monarch", "레거시 군주"],
  knightF: ["blue_green", "블루-그린 배포"],
  knightM: ["zero_downtime", "무중단 배포"],
  lancer: ["zero_day", "제로데이"],
  maskDude: ["anon_commit", "익명 커밋"],
  medievalKing: ["feudal_arch", "봉건 아키텍처"],
  monk: ["zen_mode", "젠 모드"],
  mrMochi: ["infinite_scroll", "무한 스크롤"],
  ninjaFrog: ["stealth_deploy", "은신 배포"],
  ogre: ["monolith", "모놀리스"],
  orc: ["brute_merge", "강제 머지"],
  pawn: ["merge_conflict", "머지 컨플릭트"],
  pirateCaptain: ["code_plunder", "코드 약탈"],
  plant: ["dependency_tree", "의존성 트리"],
  princessSera: ["graceful_shutdown", "우아한 종료"],
  pterodactyl: ["race_condition", "레이스 컨디션"],
  roboRetro: ["quantization", "양자화"],
  skeletonLord: ["dead_code", "데드 코드"],
  skull: ["segfault", "세그폴트"],
  tRex: ["extinction_event", "레거시 멸종"],
  visorBot: ["gradient_explosion", "그래디언트 폭발"],
  warrior: ["fullstack_smash", "풀스택 강타"],
  whale: ["docker_whale", "도커 웨일"],
  wizardM: ["hallucination", "환각 시전"],
};

// 베이스 스킬 per-kind 배정(id, name) — Swift 배정 공식의 resolved 산출물(카탈로그 다양화).
// 타입은 battleTypeOf 파생·power/rider는 상수(pvp_policy). 드리프트는 PARITYBASE 골든이 잠금.
export const GENERIC_SKILL: Record<string,[string,string]> = {
  agentMike: ["off_and_on", "껐다 켜기"],
  akita: ["hotfix", "핫픽스"],
  angel: ["console_log_spam", "console.log 도배"],
  angie: ["retry_loop", "일단 재시도"],
  angryPig: ["off_and_on", "껐다 켜기"],
  antennaBot: ["rubber_duck", "러버덕 디버깅"],
  archer: ["off_and_on", "껐다 켜기"],
  armand: ["printf_debug", "printf 디버깅"],
  baldPirate: ["off_and_on", "껐다 켜기"],
  ballooney: ["cache_purge", "캐시 삭제"],
  barryCherry: ["todo_later", "TODO: 나중에"],
  bat: ["git_blame", "git blame"],
  batBot: ["hotfix", "핫픽스"],
  beaconBot: ["printf_debug", "printf 디버깅"],
  bear: ["stackoverflow_paste", "스택오버플로 복붙"],
  bee: ["rubber_duck", "러버덕 디버깅"],
  bigDemon: ["regenerate", "다시 생성"],
  bigGuy: ["git_blame", "git blame"],
  bigRed: ["cache_purge", "캐시 삭제"],
  bigZombie: ["retry_loop", "일단 재시도"],
  blankey: ["todo_later", "TODO: 나중에"],
  blockyBub: ["rubber_duck", "러버덕 디버깅"],
  blueBird: ["console_log_spam", "console.log 도배"],
  boar: ["off_and_on", "껐다 켜기"],
  bombGuy: ["stackoverflow_paste", "스택오버플로 복붙"],
  bub: ["off_and_on", "껐다 켜기"],
  bumpyBot: ["regenerate", "다시 생성"],
  bunny: ["rubber_duck", "러버덕 디버깅"],
  bushly: ["cache_purge", "캐시 삭제"],
  cat1: ["rubber_duck", "러버덕 디버깅"],
  cat2: ["console_log_spam", "console.log 도배"],
  cat3: ["retry_loop", "일단 재시도"],
  cat4: ["todo_later", "TODO: 나중에"],
  cat5: ["ctrl_cv", "Ctrl+C Ctrl+V"],
  cat6: ["regenerate", "다시 생성"],
  caveGirl: ["rubber_duck", "러버덕 디버깅"],
  caveGirl1: ["console_log_spam", "console.log 도배"],
  caverman: ["git_blame", "git blame"],
  chameleon: ["ctrl_cv", "Ctrl+C Ctrl+V"],
  cheesePuff: ["hotfix", "핫픽스"],
  chiChiBird: ["regenerate", "다시 생성"],
  chicken: ["retry_loop", "일단 재시도"],
  chort: ["rubber_duck", "러버덕 디버깅"],
  clownCaptain: ["retry_loop", "일단 재시도"],
  cucumber: ["cache_purge", "캐시 삭제"],
  daikon: ["ctrl_cv", "Ctrl+C Ctrl+V"],
  deer: ["cache_purge", "캐시 삭제"],
  devoDevil: ["stackoverflow_paste", "스택오버플로 복붙"],
  diego: ["retry_loop", "일단 재시도"],
  dinoBat: ["cache_purge", "캐시 삭제"],
  dinoBug: ["stackoverflow_paste", "스택오버플로 복붙"],
  dinoDragon: ["regenerate", "다시 생성"],
  dinoLizard: ["hotfix", "핫픽스"],
  dinoPlant: ["printf_debug", "printf 디버깅"],
  dinoTurtle: ["off_and_on", "껐다 켜기"],
  diverFish: ["stackoverflow_paste", "스택오버플로 복붙"],
  doc: ["rubber_duck", "러버덕 디버깅"],
  dragonMan: ["retry_loop", "일단 재시도"],
  duck: ["todo_later", "TODO: 나중에"],
  dwarfF: ["printf_debug", "printf 디버깅"],
  dwarfM: ["stackoverflow_paste", "스택오버플로 복붙"],
  elfF: ["off_and_on", "껐다 켜기"],
  elfM: ["cache_purge", "캐시 삭제"],
  evilWizard: ["off_and_on", "껐다 켜기"],
  fairy: ["console_log_spam", "console.log 도배"],
  fantasyWarrior: ["rubber_duck", "러버덕 디버깅"],
  fatBird: ["ctrl_cv", "Ctrl+C Ctrl+V"],
  fierceTooth: ["todo_later", "TODO: 나중에"],
  fireWorm: ["console_log_spam", "console.log 도배"],
  flyingEye: ["off_and_on", "껐다 켜기"],
  fox: ["hotfix", "핫픽스"],
  geralt: ["console_log_spam", "console.log 도배"],
  ghost: ["printf_debug", "printf 디버깅"],
  giantRat: ["ctrl_cv", "Ctrl+C Ctrl+V"],
  gloppySlime: ["git_blame", "git blame"],
  goblin: ["stackoverflow_paste", "스택오버플로 복붙"],
  goblinBrute: ["cache_purge", "캐시 삭제"],
  goldenRetriever: ["printf_debug", "printf 디버깅"],
  gordon: ["ctrl_cv", "Ctrl+C Ctrl+V"],
  greatDane: ["stackoverflow_paste", "스택오버플로 복붙"],
  grizzly: ["retry_loop", "일단 재시도"],
  gumBot: ["cache_purge", "캐시 삭제"],
  hermie: ["cache_purge", "캐시 삭제"],
  heroKnight: ["printf_debug", "printf 디버깅"],
  holly: ["todo_later", "TODO: 나중에"],
  huntress: ["stackoverflow_paste", "스택오버플로 복붙"],
  husky: ["git_blame", "git blame"],
  iceZombie: ["rubber_duck", "러버덕 디버깅"],
  imp: ["retry_loop", "일단 재시도"],
  jellySlime: ["console_log_spam", "console.log 도배"],
  jumpyLumpy: ["git_blame", "git blame"],
  kingHuman: ["retry_loop", "일단 재시도"],
  kingPig: ["cache_purge", "캐시 삭제"],
  kingSlime: ["regenerate", "다시 생성"],
  knightF: ["git_blame", "git blame"],
  knightM: ["rubber_duck", "러버덕 디버깅"],
  lancer: ["printf_debug", "printf 디버깅"],
  lilWiz: ["todo_later", "TODO: 나중에"],
  lionWarrior: ["todo_later", "TODO: 나중에"],
  littleCaveBoy: ["ctrl_cv", "Ctrl+C Ctrl+V"],
  lizardF: ["hotfix", "핫픽스"],
  lizardM: ["printf_debug", "printf 디버깅"],
  martialHero: ["git_blame", "git blame"],
  martianRed: ["off_and_on", "껐다 켜기"],
  maskDude: ["regenerate", "다시 생성"],
  maskedOrc: ["todo_later", "TODO: 나중에"],
  medievalKing: ["cache_purge", "캐시 삭제"],
  mimic: ["todo_later", "TODO: 나중에"],
  miniBot: ["ctrl_cv", "Ctrl+C Ctrl+V"],
  miniRex: ["todo_later", "TODO: 나중에"],
  moeScotty: ["console_log_spam", "console.log 도배"],
  monk: ["stackoverflow_paste", "스택오버플로 복붙"],
  mrChomps: ["git_blame", "git blame"],
  mrCircuit: ["console_log_spam", "console.log 도배"],
  mrMan: ["ctrl_cv", "Ctrl+C Ctrl+V"],
  mrMochi: ["retry_loop", "일단 재시도"],
  muddy: ["todo_later", "TODO: 나중에"],
  mushroom: ["retry_loop", "일단 재시도"],
  myconid: ["git_blame", "git blame"],
  necromancer: ["off_and_on", "껐다 켜기"],
  ninjaFrog: ["hotfix", "핫픽스"],
  octi: ["todo_later", "TODO: 나중에"],
  ogre: ["hotfix", "핫픽스"],
  onionLad: ["console_log_spam", "console.log 도배"],
  oposum: ["todo_later", "TODO: 나중에"],
  orangeFruit: ["rubber_duck", "러버덕 디버깅"],
  orc: ["off_and_on", "껐다 켜기"],
  orcShaman: ["ctrl_cv", "Ctrl+C Ctrl+V"],
  orcWarrior: ["regenerate", "다시 생성"],
  orchidOwl: ["hotfix", "핫픽스"],
  pawn: ["cache_purge", "캐시 삭제"],
  penguin: ["printf_debug", "printf 디버깅"],
  percy: ["console_log_spam", "console.log 도배"],
  pig: ["git_blame", "git blame"],
  pigBomber: ["console_log_spam", "console.log 도배"],
  pigBoxer: ["rubber_duck", "러버덕 디버깅"],
  pirateCaptain: ["rubber_duck", "러버덕 디버깅"],
  pixelBot: ["console_log_spam", "console.log 도배"],
  plant: ["ctrl_cv", "Ctrl+C Ctrl+V"],
  pokeyBub: ["git_blame", "git blame"],
  princessSera: ["hotfix", "핫픽스"],
  pterodactyl: ["ctrl_cv", "Ctrl+C Ctrl+V"],
  pumpkinDude: ["console_log_spam", "console.log 도배"],
  rabbit: ["git_blame", "git blame"],
  radish: ["regenerate", "다시 생성"],
  rino: ["console_log_spam", "console.log 도배"],
  roach: ["git_blame", "git blame"],
  roboPumpkin: ["stackoverflow_paste", "스택오버플로 복붙"],
  roboRetro: ["retry_loop", "일단 재시도"],
  roboTotem: ["off_and_on", "껐다 켜기"],
  robotJ5: ["git_blame", "git blame"],
  robotWalky: ["rubber_duck", "러버덕 디버깅"],
  rock1: ["printf_debug", "printf 디버깅"],
  rock2: ["stackoverflow_paste", "스택오버플로 복붙"],
  rock3: ["off_and_on", "껐다 켜기"],
  rocketCherry: ["regenerate", "다시 생성"],
  rollingNero: ["printf_debug", "printf 디버깅"],
  saintBernard: ["off_and_on", "껐다 켜기"],
  schnauzer: ["cache_purge", "캐시 삭제"],
  scrapBot: ["git_blame", "git blame"],
  sentryBot: ["todo_later", "TODO: 나중에"],
  skelet: ["cache_purge", "캐시 삭제"],
  skeletonG: ["ctrl_cv", "Ctrl+C Ctrl+V"],
  skeletonLord: ["rubber_duck", "러버덕 디버깅"],
  skull: ["stackoverflow_paste", "스택오버플로 복붙"],
  slime: ["todo_later", "TODO: 나중에"],
  slug: ["printf_debug", "printf 디버깅"],
  snail: ["hotfix", "핫픽스"],
  snipCrab: ["off_and_on", "껐다 켜기"],
  spiderBot: ["retry_loop", "일단 재시도"],
  spikeyBub: ["cache_purge", "캐시 삭제"],
  squirmyWormy: ["rubber_duck", "러버덕 디버깅"],
  sunFox: ["ctrl_cv", "Ctrl+C Ctrl+V"],
  sunFrog: ["retry_loop", "일단 재시도"],
  swampy: ["ctrl_cv", "Ctrl+C Ctrl+V"],
  tRex: ["retry_loop", "일단 재시도"],
  tinySlug: ["stackoverflow_paste", "스택오버플로 복붙"],
  tinyZombie: ["git_blame", "git blame"],
  toggle: ["regenerate", "다시 생성"],
  tommy: ["stackoverflow_paste", "스택오버플로 복붙"],
  tracy: ["hotfix", "핫픽스"],
  trunk: ["hotfix", "핫픽스"],
  turtle: ["regenerate", "다시 생성"],
  twiggy: ["printf_debug", "printf 디버깅"],
  vampireBat: ["retry_loop", "일단 재시도"],
  vessa: ["retry_loop", "일단 재시도"],
  visorBot: ["regenerate", "다시 생성"],
  warrior: ["hotfix", "핫픽스"],
  whale: ["console_log_spam", "console.log 도배"],
  wispyFire: ["rubber_duck", "러버덕 디버깅"],
  wizardF: ["cache_purge", "캐시 삭제"],
  wizardM: ["git_blame", "git blame"],
  wogol: ["printf_debug", "printf 디버깅"],
  wolf: ["printf_debug", "printf 디버깅"],
  zombie: ["console_log_spam", "console.log 도배"],
};

export const TYPE_SKILL: Record<string,[string,string]> = {
  agentMike: ["lgtm", "LGTM"],
  akita: ["mem_leak", "메모리 릭"],
  angel: ["context_overflow", "컨텍스트 폭발"],
  angie: ["context_overflow", "컨텍스트 폭발"],
  angryPig: ["mem_leak", "메모리 릭"],
  antennaBot: ["retry_storm", "리트라이 폭풍"],
  archer: ["breaking_change", "브레이킹 체인지"],
  armand: ["prod_hotpatch", "프로드 직수정"],
  baldPirate: ["hard_reset", "hard reset"],
  ballooney: ["pair_programming", "페어 프로그래밍"],
  barryCherry: ["daily_standup", "데일리 스탠드업"],
  bat: ["mem_leak", "메모리 릭"],
  batBot: ["retry_storm", "리트라이 폭풍"],
  beaconBot: ["cron_avalanche", "크론 눈사태"],
  bear: ["fork_bomb", "포크 폭탄"],
  bee: ["cpu_spike", "CPU 스파이크"],
  bigDemon: ["heisenbug", "하이젠버그"],
  bigGuy: ["breaking_change", "브레이킹 체인지"],
  bigRed: ["cascade_failure", "연쇄 장애"],
  bigZombie: ["flaky_test", "플레이키 테스트"],
  blankey: ["friday_deploy", "금요일 배포"],
  blockyBub: ["onboarding", "온보딩"],
  blueBird: ["fork_bomb", "포크 폭탄"],
  boar: ["disk_full", "디스크 100%"],
  bombGuy: ["force_push", "강제 푸시"],
  bub: ["lgtm", "LGTM"],
  bumpyBot: ["lgtm", "LGTM"],
  bunny: ["mem_leak", "메모리 릭"],
  bushly: ["temperature_max", "temperature 1.0"],
  cat1: ["mem_leak", "메모리 릭"],
  cat2: ["cpu_spike", "CPU 스파이크"],
  cat3: ["fork_bomb", "포크 폭탄"],
  cat4: ["disk_full", "디스크 100%"],
  cat5: ["swap_thrash", "스왑 지옥"],
  cat6: ["thread_stampede", "스레드 폭주"],
  caveGirl: ["swap_thrash", "스왑 지옥"],
  caveGirl1: ["thread_stampede", "스레드 폭주"],
  caverman: ["disk_full", "디스크 100%"],
  chameleon: ["mem_leak", "메모리 릭"],
  cheesePuff: ["pair_programming", "페어 프로그래밍"],
  chiChiBird: ["mem_leak", "메모리 릭"],
  chicken: ["disk_full", "디스크 100%"],
  chort: ["friday_deploy", "금요일 배포"],
  clownCaptain: ["hard_reset", "hard reset"],
  cucumber: ["sudo_strike", "sudo 일격"],
  daikon: ["onboarding", "온보딩"],
  deer: ["swap_thrash", "스왑 지옥"],
  devoDevil: ["friday_deploy", "금요일 배포"],
  diego: ["prod_hotpatch", "프로드 직수정"],
  dinoBat: ["fork_bomb", "포크 폭탄"],
  dinoBug: ["mem_leak", "메모리 릭"],
  dinoDragon: ["disk_full", "디스크 100%"],
  dinoLizard: ["swap_thrash", "스왑 지옥"],
  dinoPlant: ["thread_stampede", "스레드 폭주"],
  dinoTurtle: ["cpu_spike", "CPU 스파이크"],
  diverFish: ["onboarding", "온보딩"],
  doc: ["temperature_max", "temperature 1.0"],
  dragonMan: ["mem_leak", "메모리 릭"],
  duck: ["swap_thrash", "스왑 지옥"],
  dwarfF: ["sudo_strike", "sudo 일격"],
  dwarfM: ["breaking_change", "브레이킹 체인지"],
  elfF: ["prod_hotpatch", "프로드 직수정"],
  elfM: ["force_push", "강제 푸시"],
  evilWizard: ["sudo_strike", "sudo 일격"],
  fairy: ["temperature_max", "temperature 1.0"],
  fantasyWarrior: ["force_push", "강제 푸시"],
  fatBird: ["thread_stampede", "스레드 폭주"],
  fierceTooth: ["sudo_strike", "sudo 일격"],
  fireWorm: ["friday_deploy", "금요일 배포"],
  flyingEye: ["friday_deploy", "금요일 배포"],
  fox: ["mem_leak", "메모리 릭"],
  geralt: ["breaking_change", "브레이킹 체인지"],
  ghost: ["friday_deploy", "금요일 배포"],
  giantRat: ["flaky_test", "플레이키 테스트"],
  gloppySlime: ["context_overflow", "컨텍스트 폭발"],
  goblin: ["force_push", "강제 푸시"],
  goblinBrute: ["heisenbug", "하이젠버그"],
  goldenRetriever: ["cpu_spike", "CPU 스파이크"],
  gordon: ["hard_reset", "hard reset"],
  greatDane: ["fork_bomb", "포크 폭탄"],
  grizzly: ["fork_bomb", "포크 폭탄"],
  gumBot: ["cron_avalanche", "크론 눈사태"],
  hermie: ["mem_leak", "메모리 릭"],
  heroKnight: ["force_push", "강제 푸시"],
  holly: ["force_push", "강제 푸시"],
  huntress: ["hard_reset", "hard reset"],
  husky: ["thread_stampede", "스레드 폭주"],
  iceZombie: ["heisenbug", "하이젠버그"],
  imp: ["cascade_failure", "연쇄 장애"],
  jellySlime: ["onboarding", "온보딩"],
  jumpyLumpy: ["daily_standup", "데일리 스탠드업"],
  kingHuman: ["hallucinated_api", "존재하지 않는 API"],
  kingPig: ["cpu_spike", "CPU 스파이크"],
  kingSlime: ["friday_deploy", "금요일 배포"],
  knightF: ["hard_reset", "hard reset"],
  knightM: ["sudo_strike", "sudo 일격"],
  lancer: ["hard_reset", "hard reset"],
  lilWiz: ["temperature_max", "temperature 1.0"],
  lionWarrior: ["cpu_spike", "CPU 스파이크"],
  littleCaveBoy: ["fork_bomb", "포크 폭탄"],
  lizardF: ["breaking_change", "브레이킹 체인지"],
  lizardM: ["prod_hotpatch", "프로드 직수정"],
  martialHero: ["prod_hotpatch", "프로드 직수정"],
  martianRed: ["heisenbug", "하이젠버그"],
  maskDude: ["force_push", "강제 푸시"],
  maskedOrc: ["force_push", "강제 푸시"],
  medievalKing: ["breaking_change", "브레이킹 체인지"],
  mimic: ["cascade_failure", "연쇄 장애"],
  miniBot: ["cron_avalanche", "크론 눈사태"],
  miniRex: ["cpu_spike", "CPU 스파이크"],
  moeScotty: ["disk_full", "디스크 100%"],
  monk: ["sudo_strike", "sudo 일격"],
  mrChomps: ["flaky_test", "플레이키 테스트"],
  mrCircuit: ["cron_avalanche", "크론 눈사태"],
  mrMan: ["onboarding", "온보딩"],
  mrMochi: ["pair_programming", "페어 프로그래밍"],
  muddy: ["flaky_test", "플레이키 테스트"],
  mushroom: ["context_overflow", "컨텍스트 폭발"],
  myconid: ["cascade_failure", "연쇄 장애"],
  necromancer: ["cascade_failure", "연쇄 장애"],
  ninjaFrog: ["hard_reset", "hard reset"],
  octi: ["daily_standup", "데일리 스탠드업"],
  ogre: ["cascade_failure", "연쇄 장애"],
  onionLad: ["lgtm", "LGTM"],
  oposum: ["pair_programming", "페어 프로그래밍"],
  orangeFruit: ["onboarding", "온보딩"],
  orc: ["hard_reset", "hard reset"],
  orcShaman: ["hard_reset", "hard reset"],
  orcWarrior: ["sudo_strike", "sudo 일격"],
  orchidOwl: ["cpu_spike", "CPU 스파이크"],
  pawn: ["prod_hotpatch", "프로드 직수정"],
  penguin: ["fork_bomb", "포크 폭탄"],
  percy: ["lgtm", "LGTM"],
  pig: ["fork_bomb", "포크 폭탄"],
  pigBomber: ["swap_thrash", "스왑 지옥"],
  pigBoxer: ["disk_full", "디스크 100%"],
  pirateCaptain: ["prod_hotpatch", "프로드 직수정"],
  pixelBot: ["cron_avalanche", "크론 눈사태"],
  plant: ["temperature_max", "temperature 1.0"],
  pokeyBub: ["daily_standup", "데일리 스탠드업"],
  princessSera: ["pair_programming", "페어 프로그래밍"],
  pterodactyl: ["fork_bomb", "포크 폭탄"],
  pumpkinDude: ["heisenbug", "하이젠버그"],
  rabbit: ["thread_stampede", "스레드 폭주"],
  radish: ["context_overflow", "컨텍스트 폭발"],
  rino: ["cpu_spike", "CPU 스파이크"],
  roach: ["cpu_spike", "CPU 스파이크"],
  roboPumpkin: ["regression_sweep", "회귀 스윕"],
  roboRetro: ["regression_sweep", "회귀 스윕"],
  roboTotem: ["retry_storm", "리트라이 폭풍"],
  robotJ5: ["regression_sweep", "회귀 스윕"],
  robotWalky: ["retry_storm", "리트라이 폭풍"],
  rock1: ["temperature_max", "temperature 1.0"],
  rock2: ["context_overflow", "컨텍스트 폭발"],
  rock3: ["hallucinated_api", "존재하지 않는 API"],
  rocketCherry: ["lgtm", "LGTM"],
  rollingNero: ["daily_standup", "데일리 스탠드업"],
  saintBernard: ["disk_full", "디스크 100%"],
  schnauzer: ["swap_thrash", "스왑 지옥"],
  scrapBot: ["regression_sweep", "회귀 스윕"],
  sentryBot: ["retry_storm", "리트라이 폭풍"],
  skelet: ["flaky_test", "플레이키 테스트"],
  skeletonG: ["heisenbug", "하이젠버그"],
  skeletonLord: ["flaky_test", "플레이키 테스트"],
  skull: ["heisenbug", "하이젠버그"],
  slime: ["hallucinated_api", "존재하지 않는 API"],
  slug: ["disk_full", "디스크 100%"],
  snail: ["fork_bomb", "포크 폭탄"],
  snipCrab: ["thread_stampede", "스레드 폭주"],
  spiderBot: ["regression_sweep", "회귀 스윕"],
  spikeyBub: ["pair_programming", "페어 프로그래밍"],
  squirmyWormy: ["fork_bomb", "포크 폭탄"],
  sunFox: ["daily_standup", "데일리 스탠드업"],
  sunFrog: ["lgtm", "LGTM"],
  swampy: ["friday_deploy", "금요일 배포"],
  tRex: ["mem_leak", "메모리 릭"],
  tinySlug: ["swap_thrash", "스왑 지옥"],
  tinyZombie: ["friday_deploy", "금요일 배포"],
  toggle: ["sudo_strike", "sudo 일격"],
  tommy: ["onboarding", "온보딩"],
  tracy: ["breaking_change", "브레이킹 체인지"],
  trunk: ["hallucinated_api", "존재하지 않는 API"],
  turtle: ["cpu_spike", "CPU 스파이크"],
  twiggy: ["daily_standup", "데일리 스탠드업"],
  vampireBat: ["heisenbug", "하이젠버그"],
  vessa: ["pair_programming", "페어 프로그래밍"],
  visorBot: ["regression_sweep", "회귀 스윕"],
  warrior: ["force_push", "강제 푸시"],
  whale: ["force_push", "강제 푸시"],
  wispyFire: ["hallucinated_api", "존재하지 않는 API"],
  wizardF: ["context_overflow", "컨텍스트 폭발"],
  wizardM: ["hallucinated_api", "존재하지 않는 API"],
  wogol: ["flaky_test", "플레이키 테스트"],
  wolf: ["cpu_spike", "CPU 스파이크"],
  zombie: ["cascade_failure", "연쇄 장애"],
};
